package kitexx

import (
	"context"
	"regexp"
	"strings"

	"github.com/cloudwego/kitex/pkg/endpoint"
	"github.com/cloudwego/kitex/pkg/kerrors"
	"github.com/cloudwego/kitex/pkg/rpcinfo"
)

// CodeBadParam is the business code of a request that fails validation
// (idl/errors.md 1001): the message names the field and the rule.
const CodeBadParam int32 = 1001

// validatable is what thrift-gen-validator gives every request struct
// whose IDL carries vt.* annotations (`kitex --thrift-plugin validator`).
type validatable interface {
	IsValid() error
}

// ValidationMiddleware checks the request before the handler runs: a
// request type with IsValid (the IDL's vt.* annotations, generated by
// thrift-gen-validator) that fails is answered with business code 1001
// and a message like "username: min_size rule failed, current value: 2".
// A request without annotations passes untouched. Installed by Options.
//
// ValidationMiddleware 在 handler 之前校验请求：IDL 里写了 vt.* 注解的请求（thrift-gen-validator
// 生成 IsValid）不合规时回业务码 1001，消息带字段名和规则。没注解的请求原样通过。
func ValidationMiddleware() endpoint.Middleware {
	return func(next endpoint.Endpoint) endpoint.Endpoint {
		return func(ctx context.Context, req, resp any) error {
			if v, ok := firstArgument(req).(validatable); ok {
				if err := v.IsValid(); err != nil {
					return BizError(ctx, kerrors.NewBizStatusError(CodeBadParam, FriendlyValidation(err.Error())))
				}
			}
			return next(ctx, req, resp)
		}
	}
}

// BizError is how a server middleware answers with a business code. Kitex
// turns a BizStatusError into a TTHeader status only when the handler
// returns it; one returned by a middleware would reach the client as a
// transport error ("remote or network error") and the gateway would say
// 5001. So the middleware sets it on the RPC info itself and returns nil,
// which is what the client decodes as the business error.
//
// BizError 是服务端中间件回业务码的方式：Kitex 只把 handler 返回的 BizStatusError 转成
// TTHeader 状态，中间件直接返回的会变成传输错误（网关看到 5001）；所以这里把它写进 rpcinfo
// 再返回 nil，客户端就按业务错误解码。
func BizError(ctx context.Context, err error) error {
	biz, ok := kerrors.FromBizStatusError(err)
	if !ok {
		return err
	}
	if ri := rpcinfo.GetRPCInfo(ctx); ri != nil {
		if setter, ok := ri.Invocation().(rpcinfo.InvocationSetter); ok {
			setter.SetBizStatusErr(biz)
			return nil
		}
	}
	return err
}

var validatorMsg = regexp.MustCompile(`^field (\w+) (.*)$`)

// FriendlyValidation turns thrift-gen-validator's "field Username min_size
// rule failed, current value: 2" into "username: min_size rule failed,
// current value: 2": the field as the client knows it (snake_case).
func FriendlyValidation(msg string) string {
	m := validatorMsg.FindStringSubmatch(strings.TrimSpace(msg))
	if m == nil {
		return msg
	}
	return snake(m[1]) + ": " + m[2]
}

func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				prev := rune(s[i-1])
				if prev < 'A' || prev > 'Z' {
					b.WriteByte('_')
				}
			}
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return strings.TrimSuffix(b.String(), "_")
}
