package kitexx

import (
	"context"
	"regexp"
	"strings"

	"github.com/cloudwego/kitex/pkg/endpoint"
	"github.com/cloudwego/kitex/pkg/kerrors"
)

// CodeBadParam is the business code of a request that fails validation
// (idl/errors.md 1001): the message names the field and the rule.
const CodeBadParam int32 = 1001

// validatable is what thrift-gen-validator gives every request struct
// whose IDL carries vt.* annotations (`kitex --thrift-plugin validator`).
type validatable interface {
	IsValid() error
}

// ValidationMiddleware checks the request before the handler runs: a
// request type with IsValid (the IDL's vt.* annotations, generated by
// thrift-gen-validator) that fails is answered with business code 1001
// and a message like "username: min_size rule failed, current value: 2".
// A request without annotations passes untouched. Installed by Options.
//
// ValidationMiddleware 在 handler 之前校验请求：IDL 里写了 vt.* 注解的请求（thrift-gen-validator
// 生成 IsValid）不合规时回业务码 1001，消息带字段名和规则。没注解的请求原样通过。
func ValidationMiddleware() endpoint.Middleware {
	return func(next endpoint.Endpoint) endpoint.Endpoint {
		return func(ctx context.Context, req, resp any) error {
			if v, ok := firstArgument(req).(validatable); ok {
				if err := v.IsValid(); err != nil {
					return kerrors.NewBizStatusError(CodeBadParam, FriendlyValidation(err.Error()))
				}
			}
			return next(ctx, req, resp)
		}
	}
}

var validatorMsg = regexp.MustCompile(`^field (\w+) (.*)$`)

// FriendlyValidation turns thrift-gen-validator's "field Username min_size
// rule failed, current value: 2" into "username: min_size rule failed,
// current value: 2": the field as the client knows it (snake_case).
func FriendlyValidation(msg string) string {
	m := validatorMsg.FindStringSubmatch(strings.TrimSpace(msg))
	if m == nil {
		return msg
	}
	return snake(m[1]) + ": " + m[2]
}

func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				prev := rune(s[i-1])
				if prev < 'A' || prev > 'Z' {
					b.WriteByte('_')
				}
			}
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return strings.TrimSuffix(b.String(), "_")
}
