package main

import (
	"strings"
	"testing"
)

func TestAnnotateOnlyBareStructFields(t *testing.T) {
	in := `namespace go x
struct Req {
    1: i64 uid (api.body="uid")
    2: string name // comment
    3: optional list<string> tags,
}
service S {
    Resp Do(1: Req req) (api.post="/v1/x")
}
`
	out := string(Annotate([]byte(in)))
	for _, want := range []string{`1: i64 uid (api.body="uid")`, `2: string name (api.body="name")  // comment`, `3: optional list<string> tags (api.body="tags"),`, `Resp Do(1: Req req) (api.post="/v1/x")`} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in:\n%s", want, out)
		}
	}
}

func TestPatchInfo(t *testing.T) {
	out, err := Patch([]byte("openapi: 3.0.3\ninfo:\n  title: API generated by thrift-gen-http-swagger\n  description: API description\n  version: 0.0.1\npaths: {}\n"), "ser-api", "v1.2.3", "", "x", Directives{})
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	if !strings.Contains(s, "title: ser-api") || !strings.Contains(s, "version: v1.2.3") || strings.Contains(s, "API description") {
		t.Errorf("%s", s)
	}
}

func TestLocalize(t *testing.T) {
	src := []byte("// @docs title: 玩家网关\n// @docs description: 所有接口。\n// @docs tag member: 会员\n// @docs tag wallet: 钱包\nnamespace go x\n")
	d := ParseDirectives(src)
	if d.Title != "玩家网关" || d.Description != "所有接口。" || len(d.Tags) != 2 || d.Tags[1].Name != "钱包" {
		t.Fatalf("%+v", d)
	}
	doc := `openapi: 3.0.3
info:
  title: x
  version: "1"
paths:
  /ping:
    get:
      tags: [SerApiService]
      operationId: Ping
      responses:
        "200":
          description: Successful response
  /v1/member/getProfile:
    post:
      tags: [SerApiService]
      description: 取会员资料。网关调 ser-user。
      operationId: GetProfile
      responses: {}
  /v1/wallet/balance:
    post:
      tags: [SerApiService]
      operationId: Balance
      responses: {}
`
	out, err := Patch([]byte(doc), d.Title, "v1", d.Description, "x", d)
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	for _, want := range []string{"title: 玩家网关", "description: 所有接口。", "summary: 取会员资料", "description: 网关调 ser-user。", "- 会员", "- 钱包", "- 系统", "description: 成功。"} {
		if !strings.Contains(s, want) {
			t.Errorf("missing %q in:\n%s", want, s)
		}
	}
	if strings.Contains(s, "SerApiService") || strings.Contains(s, "Successful response") {
		t.Errorf("english placeholders left:\n%s", s)
	}
	top := s[strings.LastIndex(s, "\ntags:"):]
	if i, j, k := strings.Index(top, "name: 会员"), strings.Index(top, "name: 钱包"), strings.Index(top, "name: 系统"); !(i >= 0 && i < j && j < k) {
		t.Errorf("tag order: directives first, then the rest\n%s", top)
	}
}
