package main

import (
	"strings"
	"testing"
)

func TestAnnotateOnlyBareStructFields(t *testing.T) {
	in := `namespace go x
struct Req {
    1: i64 uid (api.body="uid")
    2: string name // comment
    3: optional list<string> tags,
}
service S {
    Resp Do(1: Req req) (api.post="/v1/x")
}
`
	out := string(Annotate([]byte(in)))
	for _, want := range []string{`1: i64 uid (api.body="uid")`, `2: string name (api.body="name")  // comment`, `3: optional list<string> tags (api.body="tags"),`, `Resp Do(1: Req req) (api.post="/v1/x")`} {
		if !strings.Contains(out, want) {
			t.Errorf("missing %q in:\n%s", want, out)
		}
	}
}

func TestPatchInfo(t *testing.T) {
	out, err := Patch([]byte("openapi: 3.0.3\ninfo:\n  title: API generated by thrift-gen-http-swagger\n  description: API description\n  version: 0.0.1\npaths: {}\n"), "ser-api", "v1.2.3", "", "x")
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	if !strings.Contains(s, "title: ser-api") || !strings.Contains(s, "version: v1.2.3") || strings.Contains(s, "API description") {
		t.Errorf("%s", s)
	}
}
